#!/usr/bin/env node
// Builds the release bundle consumed by the app:
//
//   dist/library/            the bundle contents (point LIBRARY_PATH here for local dev)
//   dist/<name>-<version>.tar.gz
//   dist/CHECKSUMS.txt

import { readFileSync, writeFileSync, mkdirSync, rmSync, cpSync, readdirSync, utimesSync, unlinkSync } from 'fs';
import { join, relative } from 'path';
import { execFileSync } from 'child_process';
import { createHash } from 'crypto';
import { gzipSync } from 'zlib';
import { ROOT, DATA_DIR, loadCatalogue } from './lib/load.mjs';

const pkg = JSON.parse(readFileSync(join(ROOT, 'package.json'), 'utf8'));
const version = process.env.LIBRARY_VERSION ?? pkg.version;

const DIST = join(ROOT, 'dist');
const BUNDLE = join(DIST, 'library');

const { taxonomy, providers, threats, mitigations } = loadCatalogue();

// --- manifest ---

// Ordered by id so the manifest is stable across builds. How a consumer chooses
// to order providers in its own UI, and which of them it loads eagerly, are its
// decisions to make — the catalogue has no opinion on either.
const manifestProviders = providers
  .map(({ file, data }) => ({
    id: data.provider,
    displayName: data.displayName,
    idPrefix: data.idPrefix,
    file: `technologies/${file}`,
    serviceCount: data.services.length,
  }))
  .sort((a, b) => a.id.localeCompare(b.id));

const manifest = {
  libraryVersion: version,
  providers: manifestProviders,
  threatCount: threats.threats.length,
};

// --- derived mitigation display names ---

// technologyIds is the authored field; the names are looked up from the
// technologies themselves so the two can never drift apart.
const technologyNames = new Map(
  providers.flatMap(({ data }) => data.services.map(s => [s.id, s.name]))
);

const resolvedMitigations = {
  mitigations: mitigations.mitigations.map(m => ({
    ...m,
    providerNames: m.technologyIds.map(id => technologyNames.get(id) ?? id),
  })),
};

// --- generated types ---

const union = values => values.map(v => `  | '${v}'`).join('\n');

const types = `// Generated by scripts/build.mjs from the catalogue data. Do not edit.

export type StrideCategory =
${union(taxonomy.stride.map(s => s.id))};

export type CatalogueCategory =
${union(taxonomy.categories.map(c => c.id))};

// Exactly the providers the catalogue ships. A consumer that also models entities
// of its own — external actors, user-defined technologies — widens this union on
// its own side rather than expecting members here that no provider file defines.
export type CatalogueProvider =
${union(manifestProviders.map(p => p.id))};

export type ThreatSeverity =
${union(taxonomy.severities.map(s => s.id))};

export type PathwayMitigationType =
${union(mitigations.mitigations.map(m => m.id))};

export interface ConnectionSecurity {
  enforcesEncryption?: boolean;
  internalOnly?: boolean;
}

export interface Technology {
  id: string;
  name: string;
  provider: CatalogueProvider;
  category: CatalogueCategory;
  description: string;
  threatIds: string[];
  connectionSecurity?: ConnectionSecurity;
  threatContext?: Record<string, string>;
  threatMitigations?: Record<string, string[]>;
}

export interface MitreTechnique {
  id: string;
  name: string;
  tactic: string;
}

export interface Control {
  id: string;
  description: string;
}

export interface Threat {
  id: string;
  name: string;
  description: string;
  severity: ThreatSeverity;
  stride: StrideCategory[];
  mitreTechniques: MitreTechnique[];
  controls: Control[];
  isConnectionThreat?: boolean;
  isPathwayThreat?: boolean;
  isZoneThreat?: boolean;
  zoneContext?: string;
}

export interface ProviderData {
  provider: CatalogueProvider;
  displayName: string;
  idPrefix: string;
  services: Technology[];
}

export interface ThreatLibrary {
  threats: Threat[];
}

export interface ProviderManifestEntry {
  id: CatalogueProvider;
  displayName: string;
  idPrefix: string;
  file: string;
  serviceCount: number;
}

export interface LibraryManifest {
  libraryVersion: string;
  providers: ProviderManifestEntry[];
  threatCount: number;
}

export interface PathwayMitigationDefinition {
  id: PathwayMitigationType;
  label: string;
  description: string;
  mitigatesThreatIds: string[];
  technologyIds: string[];
  /** Names of the technologies in technologyIds, resolved at build time. */
  providerNames: string[];
}
`;

// --- assemble ---

rmSync(DIST, { recursive: true, force: true });
mkdirSync(BUNDLE, { recursive: true });

cpSync(DATA_DIR, BUNDLE, { recursive: true });

// The bundle is what downstream consumers actually redistribute, so its licence
// and attribution notice have to travel with it rather than staying behind in
// the repository.
for (const file of ['LICENSE', 'NOTICE']) {
  cpSync(join(ROOT, file), join(BUNDLE, file));
}

writeFileSync(
  join(BUNDLE, 'mitigations/pathway-mitigations.json'),
  JSON.stringify(resolvedMitigations, null, 2) + '\n'
);
writeFileSync(join(BUNDLE, 'manifest.json'), JSON.stringify(manifest, null, 2) + '\n');
writeFileSync(join(BUNDLE, 'types.d.ts'), types);
writeFileSync(join(BUNDLE, 'VERSION'), `${version}\n`);

const tarball = `${pkg.name}-${version}.tar.gz`;

const FIXED_MTIME = new Date('2020-01-01T00:00:00Z');

function walk(dir) {
  return readdirSync(dir, { withFileTypes: true }).flatMap(entry => {
    const full = join(dir, entry.name);
    return entry.isDirectory() ? [full, ...walk(full)] : [full];
  });
}

const staged = walk(BUNDLE).sort();
for (const path of staged) utimesSync(path, FIXED_MTIME, FIXED_MTIME);
utimesSync(BUNDLE, FIXED_MTIME, FIXED_MTIME);

const listPath = join(DIST, '.filelist');
writeFileSync(listPath, staged.map(p => relative(BUNDLE, p)).join('\n') + '\n');

const tarPath = join(DIST, `${pkg.name}-${version}.tar`);
// --no-recursion is required because the file list names directories as well as
// their contents. Without it tar walks each listed directory *and* archives the
// files named after it, so every file lands in the archive twice — and the
// second copy is emitted as a hardlink to itself, which bsdtar refuses to
// extract ("Skipping hardlink pointing to itself").
execFileSync(
  'tar',
  ['--format=ustar', '--numeric-owner', '--owner', '0', '--group', '0',
   '--no-recursion', '-cf', tarPath, '-C', BUNDLE, '-T', listPath],
  { stdio: 'inherit' }
);
unlinkSync(listPath);

const gzipped = gzipSync(readFileSync(tarPath), { level: 9 });
writeFileSync(join(DIST, tarball), gzipped);
unlinkSync(tarPath);

const sha256 = createHash('sha256').update(gzipped).digest('hex');

writeFileSync(join(DIST, 'CHECKSUMS.txt'), `${sha256}  ${tarball}\n`);

console.log(`Built ${tarball}`);
console.log(`  version    ${version}`);
console.log(`  providers  ${manifestProviders.map(p => `${p.id}=${p.serviceCount}`).join(' ')}`);
console.log(`  threats    ${manifest.threatCount}`);
console.log(`  sha256     ${sha256}`);
